### ISSUE TITLE
Calendar sometimes includes favorited and registered but unconfirmed courses

### ISSUE THREAD

**Issue by henrikhorluck** [TUM-Dev/CalendarProxy#102]
This might not be an upstream/TUM issue with the proxy itself, but this is a quite irritating as it gives "ghost" notifications sometimes, and makes the calendar overly bloated.

**Comment by AlexPerathoner** [comment]
Had this issue as well, usually reloading the calendar a couple of times already solves it, though

**Comment by kordianbruck** [comment]
Right, but I don't think we can do much about this. Or do you have an idea on how to address this? Any specific flag we could filter on?
