### ISSUE TITLE
Calendar should strip random numbers

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/CalendarProxy#111]
![image](https://user-images.githubusercontent.com/26258709/179513089-887c9a85-5ef5-4b80-bddd-82b0b1cc9eea.png)
Would it be possible to strip leading numbers?

**Comment by kordianbruck** [comment]
Probably with a regex, but ugh, it might explode as well in the same go.

**Comment by hruzgar** [comment]
No need to use a regex.. 
Just take everything except the first 11 characters

**Comment by kordianbruck** [comment]
Only reason this is now gone would be if TUMonline changed the behavior again. If its confirmed that this is no longer a problem, we can close this out for now.
