### ISSUE TITLE
Calendar does not parse buildings in Taufkirchen/Ottobrunn

### ISSUE THREAD

**Issue by ojas121** [TUM-Dev/CalendarProxy#120]
I have a class at "00.012, Seminarraum (9377.EG.012)". According to NavigaTUM, this is at Lise-Meitner-Straße 9-11, 85521 Ottobrunn, but this does not show in the proxy calendar. 

I assume that some buildings are missing in the list of buildings held in this repo, but as a newcomer at TUM I'm not very familiar with the buildings, their numbering, and how they are parsed here. I can try to put in a PR if I get the hang of it in time, though.

**Comment by kordianbruck** [comment]
Probably need to just add it to https://github.com/TUM-Dev/CalendarProxy/blob/master/src/buildings.json

**Comment by ojas121** [comment]
#121 should hopefully be it, but I just noticed that not all rooms with a building number in buildings.json get an address (for example. Audimax im Galileo). Not sure if that would also happen in this case, but maybe I should open a different issue for that
