### ISSUE TITLE
Appointment mistakenly brought forward by 2 hours

### ISSUE THREAD

**Issue by Max-vS** [TUM-Dev/CalendarProxy#139]
The time periods of the individual courses are 2 hours too early and this is also the case with all fellow students I have asked so far.

**Comment by joschahenningsen** [comment]
Are you (and your fellow students) using iOS by chance?

**Comment by Max-vS** [comment]
Yes!

**Comment by joschahenningsen** [comment]
This is a regression that was fixed in #128. However, the new version builds a docker container with another name that the server doesn't recognize and therefore the fix was never deployed. I'm taking care of it :)

**Comment by joschahenningsen** [comment]
I deployed the latest version to the server. Can you please remove the calendar from your phone, add it again and tell me whether the issue is fixed? @Max-vS  :)

**Comment by Max-vS** [comment]
Will do. Thanks a lot!

**Comment by Max-vS** [comment]
Now it works as intended, thanks!
