### ISSUE TITLE
Not working for TUM personal

### ISSUE THREAD

**Issue by BWibo** [TUM-Dev/CalendarProxy#142]
Hey there,

I'm TUM employee.

My calender URL looks like this:
`https://campus.tum.de/tumonlinej/ws/termin/ical?pPers=XXXXXXXX&pToken=XXXXXXX`

Both the website URL parser and constructing the URL manually does not work for me. 
Manually created URL: `https://cal.tum.app/?pPers=XXXXXXXX&pToken=XXXXXXXX`

Am I doing something wrong? Or is possibly the `pPers` parameter not understood?

**Comment by kordianbruck** [comment]
Should work now. We just didn't have logic for the other parameter in our code.
