### ISSUE TITLE
Add Maschinenwesen Abbreviations

### ISSUE THREAD

**Issue by braupach** [TUM-Dev/CalendarProxy#152]
Please add following Abbreviations:

"Technische Mechanik I": "TM1",
"Technische Mechanik II": "TM2",
"Technische Mechanik 3": "TM3",
"Technische Elektrizitätslehre": "TE",
"Regelungstechnik": "RT",
"Fluidmechanik I": "FM1",
"Maschinenelemente": "ME",
"Werkstoffe des Maschinenbaus": "WK",
"Höhere Mathematik 1 für Maschinenwesen und Chemie-Ingenieurwesen": "HM1",
"Höheren Mathematik 2 für Maschinenwesen und Chemie-Ingenieurwesen": "HM2",
"Höheren Mathematik 3 für Maschinenwesen und Chemie-Ingenieurwesen": "HM3",
"Thermodynamik": "Thermo",
"Wärmetransportphänomene": "WTP",
"Maschinenzeichnen": "MZ",
"- Regeln des technischen Zeichnens (CAMPP)": "",
"Grundlagen der modernen Informationstechnik I ": "GdmIT 1",
"Grundlagen der modernen Informationstechnik": "GdmIT",
"Modellierung von Unsicherheiten und Daten im Maschinenwesen": "MUD",
"Mathematische Tools": "MTT",

"Anlagen-Zentralübung": "ZÜ"
"Kleingruppenübung": "KGÜ",
"Vertiefungsübung": "VÜ",
" Vorlesung ": "VL",
"Gruppenübung": "GÜ",
"Tutorübung": "TÜ",

Those Abbreviations _should_ work and cover the MW-Grundstudium
(I didn't test it because development isn't my strongest field lol)

**Comment by CommanderStorm** [comment]
@braupach 
Thanks, these shortcodes should be online in ± your device's cache time

**Comment by braupach** [comment]
After evaluating the results I recommend this new version:
everything changed got **** and new lines got **new**

"Technische Mechanik I ": "TM 1 ",  ****
"Technische Mechanik II ": "TM 2 ",  ****
"Technische Mechanik 3": "TM 3",  ****
"Technische Elektrizitätslehre": "TE",
"Regelungstechnik": "RT",
"Fluidmechanik I": "FM 1",  ****
"Fluidmechanik" : "FM",  **new**
"Maschinenelemente": "ME",
"Werkstoffe des Maschinenbaus": "WK",
"Höhere Mathematik 1 für Maschinenwesen und Chemie-Ingenieurwesen": "HM 1",
"Höheren Mathematik 2 für Maschinenwesen und Chemie-Ingenieurwesen": "HM 2",
"Höheren Mathematik 3 für Maschinenwesen und Chemie-Ingenieurwesen": "HM 3",
"Thermodynamik": "Thermo",
"Wärmetransportphänomene": "WTP",
"Maschinenzeichnen": "MZ",
"- Regeln des technischen Zeichnens (CAMPP)": "",
" der modernen Informationstechnik I ": "dmIT 1", ****
" der modernen Informationstechnik": "dmIT", ****
"Modellierung von Unsicherheiten und Daten im Maschinenwesen": "MUD",
"Mathematische Tools": "MTT",
"Hausaufgabentutorium": "HA TÜ", **new**


"Anlagen-Zentralübung": "ZÜ"
"Kleingruppenübung": "KGÜ",
"Vertiefungsübung": "VÜ",
" Vorlesung ": " VL ",  ****
"Gruppenübung": "GÜ",
"Tutorübung": "TÜ"

**Comment by braupach** [comment]
I also noticed: 
"Tutorübung ": "TÜ "
"Zentralübung ": "ZÜ "


Is there any way to prioritize any entries? I feel like this would solve some of the problems with singular and plural or roman numerals.

**Comment by CommanderStorm** [comment]
Currently, not priority exists.

This is because we use
https://github.com/TUM-Dev/CalendarProxy/blob/1cdccf01ffa75195b59e8c4347dd7903e99a9c70/internal/app.go#L30

replace this way
https://github.com/TUM-Dev/CalendarProxy/blob/1cdccf01ffa75195b59e8c4347dd7903e99a9c70/internal/app.go#L223-L226

and the spec for map.iter is

> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next

I guess replacing this with longest, then alphabetical key ordering would be better.

**Comment by CommanderStorm** [comment]
> I also noticed: "Tutorübung ": "TÜ " "Zentralübung ": "ZÜ "

I don't know what you mean by this comment ^^
 
> Is there any way to prioritize any entries? I feel like this would solve some of the problems with singular and plural or roman numerals.

Implmented in #154
