### ISSUE TITLE
Website und Kalendar sind weg

### ISSUE THREAD

**Issue by MaximIgenbergs** [TUM-Dev/CalendarProxy#173]
Website 404 und iCal Proxy sagt "calendar not found"

**Comment by CommanderStorm** [comment]
Interesting. Thanks for the report ^^
(TL;DR: fixed it and tested that it won't happen again)

<details><summary>Reason why monitoring did not catch it earlier is the (insane) level of false alarms and us missing a monitor for cal.tum.sexy</summary>
<p>

![image](https://github.com/TUM-Dev/CalendarProxy/assets/26258709/c54c78eb-1102-40e7-a174-42eb8474b1c0)

</p>
</details> 

The reason this happened in the first place was that we had not configured these services (tum.sexy, cal.tum.sexy) with the correct restart-policy (fun game: which of these comes back online after a restart: `restart: on-failure` vs `restart: unless-stoped` vs `restart: no`)
⇒ they stayed down after the node they are on restarting
