### ISSUE TITLE
Prefer lecture hall on multiple events

### ISSUE THREAD

**Issue by Simolation** [TUM-Dev/CalendarProxy#26]
Currently I have one lecture, that has three different locations. One in the lecture hall, one in in the interims hall and one on another campus.

The proxy selects the one at the interims hall as the default one to show on the merged event.

Would it be possible to somehow take the lecture hall as default?

**Comment by kordianbruck** [comment]
@Simolation no idea how this should work. I mean you would need to configure this somehow over the URL or you add some rind of ordering for the locations. Both options seem kinda hard to implement at the moment.

**Comment by joschahenningsen** [comment]
@kordianbruck can this be closed?

**Comment by kordianbruck** [comment]
Yeah, absolutely!
