### ISSUE TITLE
Personal appointments are missing after proxy

### ISSUE THREAD

**Issue by GeneralMine** [TUM-Dev/CalendarProxy#29]
My personal appointments are missing after using the proxy.
Without proxy they exist normally, but with proxy they are gone.

Maybe they are getting removed from the list while converting due to the custom format?

**Comment by kordianbruck** [comment]
If you can, try to add a `var_dump($allEvents)` here https://github.com/TUM-Dev/CalendarProxy/blob/master/index.php#L60 and see if those personal events are listed. Did you verify they are even outputted by the ical from campus.tum.de?

**Comment by kordianbruck** [comment]
I've just tested this and it still works. After I proxy I get this event for example:

```
BEGIN:VEVENT
UID:888101492@tum.de
DTSTART:20200505T120000Z
SEQUENCE:0
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND:20200505T140000Z
SUMMARY:Blabla
DESCRIPTION:Blabla\n
DTSTAMP:20200501T224808Z
END:VEVENT
```

**Comment by kordianbruck** [comment]
Feel free to reopen with more instructions on how to reproduce this.
