### ISSUE TITLE
[bug] Event duplicates do not get removed

### ISSUE THREAD

**Issue by cato447** [TUM-Dev/CalendarProxy#55]
When converting the calendar link from TUMonline duplicate entries do not get removed

![image](https://user-images.githubusercontent.com/47259183/133783803-82141860-e035-4368-afb0-2a485aa9d9ba.png)

**Comment by joschahenningsen** [comment]
Whould there be an "INFO" event on Monday held in Interims that was removed from the original calendar?
If yes this could be an issue: https://github.com/TUM-Dev/CalendarProxy/blob/a6aa3fda52f294077f6260e9dbf1bc6fa175db58/src/handler.php#L167

**Comment by cato447** [comment]
No, no "INFO" event is on MOnday held in Interims. Locations are: 
2300, Friedrich von Thiersch Hörsaal (0503.02.300)
MW 0001, Gustav-Niemann-Hörsaal (5510.EG.001)

**Comment by CommanderStorm** [comment]
since #60 was merged, this issue is not active anymore, or am I wrong?

**Comment by kordianbruck** [comment]
Yeah, if it still happens, users can reopen. Thanks!
