### ISSUE TITLE
[bug] locations not parsed correctly

### ISSUE THREAD

**Issue by JHthe4** [TUM-Dev/CalendarProxy#61]
There seems to have been an update to Google calendar such that our lecture locations aren't correctly parsed anymore. 

Google decides to interpret the zip code as a phone number instead of sending the location to maps to be parsed.

The bug can be seen [here](https://user-images.githubusercontent.com/9847839/139557927-c2e6a6de-15c8-45f8-833c-d729b077df40.mp4).

Don't really know how to fix this one, maybe someone has an idea how to prevent Google's overzealous phone number parsing and get the address through to maps?

**Comment by kordianbruck** [comment]
Did you click the number? There might be a different click box for the number than the actual location. Can you try clicking further left?

In order on how to fix this: probably remove the zip code and just let it guess the city name,

**Comment by JHthe4** [comment]
Yeah, I clicked on the left. It pulls you into the dialer no matter where you click, seems to be a parsing thing that Google changed. I feel like just removing the zip code is a bit of an unsatisfying and hacky solution, but if it's all we have for now I guess it could be an okay workaround. Unfortunately, I can't find any documentation on what format Google would like addresses to be passed in in iCal so that they are parsed as such. I'd be happy to implement it if you know where to find it though :).
